//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string _000000 {
            get {
                return ResourceManager.GetString("#000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string _000080 {
            get {
                return ResourceManager.GetString("#000080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkBlue.
        /// </summary>
        internal static string _00008B {
            get {
                return ResourceManager.GetString("#00008B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumBlue.
        /// </summary>
        internal static string _0000CD {
            get {
                return ResourceManager.GetString("#0000CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string _0000FF {
            get {
                return ResourceManager.GetString("#0000FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGreen.
        /// </summary>
        internal static string _006400 {
            get {
                return ResourceManager.GetString("#006400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string _008000 {
            get {
                return ResourceManager.GetString("#008000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string _008080 {
            get {
                return ResourceManager.GetString("#008080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkCyan.
        /// </summary>
        internal static string _008B8B {
            get {
                return ResourceManager.GetString("#008B8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSkyBlue.
        /// </summary>
        internal static string _00BFFF {
            get {
                return ResourceManager.GetString("#00BFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTurquoise.
        /// </summary>
        internal static string _00CED1 {
            get {
                return ResourceManager.GetString("#00CED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSpringGreen.
        /// </summary>
        internal static string _00FA9A {
            get {
                return ResourceManager.GetString("#00FA9A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string _00FF00 {
            get {
                return ResourceManager.GetString("#00FF00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpringGreen.
        /// </summary>
        internal static string _00FF7F {
            get {
                return ResourceManager.GetString("#00FF7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string _00FFFF {
            get {
                return ResourceManager.GetString("#00FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightGreen.
        /// </summary>
        internal static string _16C60C {
            get {
                return ResourceManager.GetString("#16C60C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MidnightBlue.
        /// </summary>
        internal static string _191970 {
            get {
                return ResourceManager.GetString("#191970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DodgerBlue.
        /// </summary>
        internal static string _1E90FF {
            get {
                return ResourceManager.GetString("#1E90FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSeaGreen.
        /// </summary>
        internal static string _20B2AA {
            get {
                return ResourceManager.GetString("#20B2AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForestGreen.
        /// </summary>
        internal static string _228B22 {
            get {
                return ResourceManager.GetString("#228B22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeaGreen.
        /// </summary>
        internal static string _2E8B57 {
            get {
                return ResourceManager.GetString("#2E8B57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSlateGrey.
        /// </summary>
        internal static string _2F4F4F {
            get {
                return ResourceManager.GetString("#2F4F4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimeGreen.
        /// </summary>
        internal static string _32CD32 {
            get {
                return ResourceManager.GetString("#32CD32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightBlue.
        /// </summary>
        internal static string _3B78FF {
            get {
                return ResourceManager.GetString("#3B78FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSeaGreen.
        /// </summary>
        internal static string _3CB371 {
            get {
                return ResourceManager.GetString("#3CB371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string _40E0D0 {
            get {
                return ResourceManager.GetString("#40E0D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoyalBlue.
        /// </summary>
        internal static string _4169E1 {
            get {
                return ResourceManager.GetString("#4169E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelBlue.
        /// </summary>
        internal static string _4682B4 {
            get {
                return ResourceManager.GetString("#4682B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSlateBlue.
        /// </summary>
        internal static string _483D8B {
            get {
                return ResourceManager.GetString("#483D8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumTurquoise.
        /// </summary>
        internal static string _48D1CC {
            get {
                return ResourceManager.GetString("#48D1CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string _4B0082 {
            get {
                return ResourceManager.GetString("#4B0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOliveGreen.
        /// </summary>
        internal static string _556B2F {
            get {
                return ResourceManager.GetString("#556B2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CadetBlue.
        /// </summary>
        internal static string _5F9EA0 {
            get {
                return ResourceManager.GetString("#5F9EA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightCyan.
        /// </summary>
        internal static string _61D6D6 {
            get {
                return ResourceManager.GetString("#61D6D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CornflowerBlue.
        /// </summary>
        internal static string _6495ED {
            get {
                return ResourceManager.GetString("#6495ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebeccaPurple.
        /// </summary>
        internal static string _663399 {
            get {
                return ResourceManager.GetString("#663399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumAquaMarine.
        /// </summary>
        internal static string _66CDAA {
            get {
                return ResourceManager.GetString("#66CDAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimGray.
        /// </summary>
        internal static string _696969 {
            get {
                return ResourceManager.GetString("#696969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlateBlue.
        /// </summary>
        internal static string _6A5ACD {
            get {
                return ResourceManager.GetString("#6A5ACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OliveDrab.
        /// </summary>
        internal static string _6B8E23 {
            get {
                return ResourceManager.GetString("#6B8E23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlateGray.
        /// </summary>
        internal static string _708090 {
            get {
                return ResourceManager.GetString("#708090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGray.
        /// </summary>
        internal static string _767676 {
            get {
                return ResourceManager.GetString("#767676", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSlateGrey.
        /// </summary>
        internal static string _778899 {
            get {
                return ResourceManager.GetString("#778899", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSlateBlue.
        /// </summary>
        internal static string _7B68EE {
            get {
                return ResourceManager.GetString("#7B68EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LawnGreen.
        /// </summary>
        internal static string _7CFC00 {
            get {
                return ResourceManager.GetString("#7CFC00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chartreuse.
        /// </summary>
        internal static string _7FFF00 {
            get {
                return ResourceManager.GetString("#7FFF00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine.
        /// </summary>
        internal static string _7FFFD4 {
            get {
                return ResourceManager.GetString("#7FFFD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        internal static string _800000 {
            get {
                return ResourceManager.GetString("#800000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string _800080 {
            get {
                return ResourceManager.GetString("#800080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        internal static string _808000 {
            get {
                return ResourceManager.GetString("#808000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string _808080 {
            get {
                return ResourceManager.GetString("#808080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyBlue.
        /// </summary>
        internal static string _87CEEB {
            get {
                return ResourceManager.GetString("#87CEEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSkyBlue.
        /// </summary>
        internal static string _87CEFA {
            get {
                return ResourceManager.GetString("#87CEFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueViolet.
        /// </summary>
        internal static string _8A2BE2 {
            get {
                return ResourceManager.GetString("#8A2BE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkRed.
        /// </summary>
        internal static string _8B0000 {
            get {
                return ResourceManager.GetString("#8B0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkMagenta.
        /// </summary>
        internal static string _8B008B {
            get {
                return ResourceManager.GetString("#8B008B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaddleBrown.
        /// </summary>
        internal static string _8B4513 {
            get {
                return ResourceManager.GetString("#8B4513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSeaGreen.
        /// </summary>
        internal static string _8FBC8F {
            get {
                return ResourceManager.GetString("#8FBC8F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGreen.
        /// </summary>
        internal static string _90EE90 {
            get {
                return ResourceManager.GetString("#90EE90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumPurple.
        /// </summary>
        internal static string _9370DB {
            get {
                return ResourceManager.GetString("#9370DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkViolet.
        /// </summary>
        internal static string _9400D3 {
            get {
                return ResourceManager.GetString("#9400D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleGreen.
        /// </summary>
        internal static string _98FB98 {
            get {
                return ResourceManager.GetString("#98FB98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOrchid.
        /// </summary>
        internal static string _9932CC {
            get {
                return ResourceManager.GetString("#9932CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YellowGreen.
        /// </summary>
        internal static string _9ACD32 {
            get {
                return ResourceManager.GetString("#9ACD32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        internal static string _A0522D {
            get {
                return ResourceManager.GetString("#A0522D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string _A52A2A {
            get {
                return ResourceManager.GetString("#A52A2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGrey.
        /// </summary>
        internal static string _A9A9A9 {
            get {
                return ResourceManager.GetString("#A9A9A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightBlue.
        /// </summary>
        internal static string _ADD8E6 {
            get {
                return ResourceManager.GetString("#ADD8E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenYellow.
        /// </summary>
        internal static string _ADFF2F {
            get {
                return ResourceManager.GetString("#ADFF2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleTurquoise.
        /// </summary>
        internal static string _AFEEEE {
            get {
                return ResourceManager.GetString("#AFEEEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSteelBlue.
        /// </summary>
        internal static string _B0C4DE {
            get {
                return ResourceManager.GetString("#B0C4DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowderBlue.
        /// </summary>
        internal static string _B0E0E6 {
            get {
                return ResourceManager.GetString("#B0E0E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireBrick.
        /// </summary>
        internal static string _B22222 {
            get {
                return ResourceManager.GetString("#B22222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightMagenta.
        /// </summary>
        internal static string _B4009E {
            get {
                return ResourceManager.GetString("#B4009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGoldenRod.
        /// </summary>
        internal static string _B8860B {
            get {
                return ResourceManager.GetString("#B8860B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumOrchid.
        /// </summary>
        internal static string _BA55D3 {
            get {
                return ResourceManager.GetString("#BA55D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RosyBrown.
        /// </summary>
        internal static string _BC8F8F {
            get {
                return ResourceManager.GetString("#BC8F8F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkKhaki.
        /// </summary>
        internal static string _BDB76B {
            get {
                return ResourceManager.GetString("#BDB76B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string _C0C0C0 {
            get {
                return ResourceManager.GetString("#C0C0C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumVioletRed.
        /// </summary>
        internal static string _C71585 {
            get {
                return ResourceManager.GetString("#C71585", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndianRed.
        /// </summary>
        internal static string _CD5C5C {
            get {
                return ResourceManager.GetString("#CD5C5C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string _CD853F {
            get {
                return ResourceManager.GetString("#CD853F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        internal static string _D2691E {
            get {
                return ResourceManager.GetString("#D2691E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string _D2B48C {
            get {
                return ResourceManager.GetString("#D2B48C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray.
        /// </summary>
        internal static string _D3D3D3 {
            get {
                return ResourceManager.GetString("#D3D3D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thistle.
        /// </summary>
        internal static string _D8BFD8 {
            get {
                return ResourceManager.GetString("#D8BFD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid.
        /// </summary>
        internal static string _DA70D6 {
            get {
                return ResourceManager.GetString("#DA70D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldenRod.
        /// </summary>
        internal static string _DAA520 {
            get {
                return ResourceManager.GetString("#DAA520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleVioletRed.
        /// </summary>
        internal static string _DB7093 {
            get {
                return ResourceManager.GetString("#DB7093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        internal static string _DC143C {
            get {
                return ResourceManager.GetString("#DC143C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainsboro.
        /// </summary>
        internal static string _DCDCDC {
            get {
                return ResourceManager.GetString("#DCDCDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        internal static string _DDA0DD {
            get {
                return ResourceManager.GetString("#DDA0DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BurlyWood.
        /// </summary>
        internal static string _DEB887 {
            get {
                return ResourceManager.GetString("#DEB887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightCyan.
        /// </summary>
        internal static string _E0FFFF {
            get {
                return ResourceManager.GetString("#E0FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        internal static string _E6E6FA {
            get {
                return ResourceManager.GetString("#E6E6FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightRed.
        /// </summary>
        internal static string _E74856 {
            get {
                return ResourceManager.GetString("#E74856", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSalmon.
        /// </summary>
        internal static string _E9967A {
            get {
                return ResourceManager.GetString("#E9967A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string _EE82EE {
            get {
                return ResourceManager.GetString("#EE82EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleGoldenRod.
        /// </summary>
        internal static string _EEE8AA {
            get {
                return ResourceManager.GetString("#EEE8AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightCoral.
        /// </summary>
        internal static string _F08080 {
            get {
                return ResourceManager.GetString("#F08080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaki.
        /// </summary>
        internal static string _F0E68C {
            get {
                return ResourceManager.GetString("#F0E68C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliceBlue.
        /// </summary>
        internal static string _F0F8FF {
            get {
                return ResourceManager.GetString("#F0F8FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoneyDew.
        /// </summary>
        internal static string _F0FFF0 {
            get {
                return ResourceManager.GetString("#F0FFF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string _F0FFFF {
            get {
                return ResourceManager.GetString("#F0FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandyBrown.
        /// </summary>
        internal static string _F4A460 {
            get {
                return ResourceManager.GetString("#F4A460", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string _F5DEB3 {
            get {
                return ResourceManager.GetString("#F5DEB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string _F5F5DC {
            get {
                return ResourceManager.GetString("#F5F5DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhiteSmoke.
        /// </summary>
        internal static string _F5F5F5 {
            get {
                return ResourceManager.GetString("#F5F5F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MintCream.
        /// </summary>
        internal static string _F5FFFA {
            get {
                return ResourceManager.GetString("#F5FFFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GhostWhite.
        /// </summary>
        internal static string _F8F8FF {
            get {
                return ResourceManager.GetString("#F8F8FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightYellow.
        /// </summary>
        internal static string _F9F1A5 {
            get {
                return ResourceManager.GetString("#F9F1A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon.
        /// </summary>
        internal static string _FA8072 {
            get {
                return ResourceManager.GetString("#FA8072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiqueWhite.
        /// </summary>
        internal static string _FAEBD7 {
            get {
                return ResourceManager.GetString("#FAEBD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linen.
        /// </summary>
        internal static string _FAF0E6 {
            get {
                return ResourceManager.GetString("#FAF0E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGoldenRodYellow.
        /// </summary>
        internal static string _FAFAD2 {
            get {
                return ResourceManager.GetString("#FAFAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldLace.
        /// </summary>
        internal static string _FDF5E6 {
            get {
                return ResourceManager.GetString("#FDF5E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string _FF0000 {
            get {
                return ResourceManager.GetString("#FF0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string _FF00FF {
            get {
                return ResourceManager.GetString("#FF00FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepPink.
        /// </summary>
        internal static string _FF1493 {
            get {
                return ResourceManager.GetString("#FF1493", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrangeRed.
        /// </summary>
        internal static string _FF4500 {
            get {
                return ResourceManager.GetString("#FF4500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        internal static string _FF6347 {
            get {
                return ResourceManager.GetString("#FF6347", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotPink.
        /// </summary>
        internal static string _FF69B4 {
            get {
                return ResourceManager.GetString("#FF69B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral.
        /// </summary>
        internal static string _FF7F50 {
            get {
                return ResourceManager.GetString("#FF7F50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOrange.
        /// </summary>
        internal static string _FF8C00 {
            get {
                return ResourceManager.GetString("#FF8C00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSalmon.
        /// </summary>
        internal static string _FFA07A {
            get {
                return ResourceManager.GetString("#FFA07A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string _FFA500 {
            get {
                return ResourceManager.GetString("#FFA500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightPink.
        /// </summary>
        internal static string _FFB6C1 {
            get {
                return ResourceManager.GetString("#FFB6C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string _FFC0CB {
            get {
                return ResourceManager.GetString("#FFC0CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string _FFD700 {
            get {
                return ResourceManager.GetString("#FFD700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeachPuff.
        /// </summary>
        internal static string _FFDAB9 {
            get {
                return ResourceManager.GetString("#FFDAB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavajoWhite.
        /// </summary>
        internal static string _FFDEAD {
            get {
                return ResourceManager.GetString("#FFDEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moccasin.
        /// </summary>
        internal static string _FFE4B5 {
            get {
                return ResourceManager.GetString("#FFE4B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisque.
        /// </summary>
        internal static string _FFE4C4 {
            get {
                return ResourceManager.GetString("#FFE4C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MistyRose.
        /// </summary>
        internal static string _FFE4E1 {
            get {
                return ResourceManager.GetString("#FFE4E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlanchedAlmond.
        /// </summary>
        internal static string _FFEBCD {
            get {
                return ResourceManager.GetString("#FFEBCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PapayaWhip.
        /// </summary>
        internal static string _FFEFD5 {
            get {
                return ResourceManager.GetString("#FFEFD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LavenderBlush.
        /// </summary>
        internal static string _FFF0F5 {
            get {
                return ResourceManager.GetString("#FFF0F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeaShell.
        /// </summary>
        internal static string _FFF5EE {
            get {
                return ResourceManager.GetString("#FFF5EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornsilk.
        /// </summary>
        internal static string _FFF8DC {
            get {
                return ResourceManager.GetString("#FFF8DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LemonChiffon.
        /// </summary>
        internal static string _FFFACD {
            get {
                return ResourceManager.GetString("#FFFACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloralWhite.
        /// </summary>
        internal static string _FFFAF0 {
            get {
                return ResourceManager.GetString("#FFFAF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string _FFFAFA {
            get {
                return ResourceManager.GetString("#FFFAFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string _FFFF00 {
            get {
                return ResourceManager.GetString("#FFFF00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightYellow.
        /// </summary>
        internal static string _FFFFE0 {
            get {
                return ResourceManager.GetString("#FFFFE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory.
        /// </summary>
        internal static string _FFFFF0 {
            get {
                return ResourceManager.GetString("#FFFFF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string _FFFFFF {
            get {
                return ResourceManager.GetString("#FFFFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O_pen.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _as.
        /// </summary>
        internal static string btnSaveAs {
            get {
                return ResourceManager.GetString("btnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_lors.
        /// </summary>
        internal static string ctxColors {
            get {
                return ResourceManager.GetString("ctxColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string ctxCopy {
            get {
                return ResourceManager.GetString("ctxCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        internal static string ctxCut {
            get {
                return ResourceManager.GetString("ctxCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete All.
        /// </summary>
        internal static string ctxDeleteAll {
            get {
                return ResourceManager.GetString("ctxDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        internal static string ctxPaste {
            get {
                return ResourceManager.GetString("ctxPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        internal static string ctxRedo {
            get {
                return ResourceManager.GetString("ctxRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select All.
        /// </summary>
        internal static string ctxSelectAll {
            get {
                return ResourceManager.GetString("ctxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        internal static string ctxUndo {
            get {
                return ResourceManager.GetString("ctxUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Picker.
        /// </summary>
        internal static string dpTitle {
            get {
                return ResourceManager.GetString("dpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Files.
        /// </summary>
        internal static string fdAnyFiles {
            get {
                return ResourceManager.GetString("fdAnyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        internal static string fdCtxDelete {
            get {
                return ResourceManager.GetString("fdCtxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide {0}.
        /// </summary>
        internal static string fdCtxHide {
            get {
                return ResourceManager.GetString("fdCtxHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        internal static string fdCtxNew {
            get {
                return ResourceManager.GetString("fdCtxNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        internal static string fdCtxRename {
            get {
                return ResourceManager.GetString("fdCtxRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort {0} ASC.
        /// </summary>
        internal static string fdCtxSortAsc {
            get {
                return ResourceManager.GetString("fdCtxSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort {0} DESC.
        /// </summary>
        internal static string fdCtxSortDesc {
            get {
                return ResourceManager.GetString("fdCtxSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;? This operation is permanent.
        /// </summary>
        internal static string fdDeleteBody {
            get {
                return ResourceManager.GetString("fdDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string fdDeleteFailedTitle {
            get {
                return ResourceManager.GetString("fdDeleteFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string fdDeleteTitle {
            get {
                return ResourceManager.GetString("fdDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string fdDirectory {
            get {
                return ResourceManager.GetString("fdDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already exists with that name.
        /// </summary>
        internal static string fdDirectoryAlreadyExistsFeedback {
            get {
                return ResourceManager.GetString("fdDirectoryAlreadyExistsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing directory.
        /// </summary>
        internal static string fdDirectoryMustExistFeedback {
            get {
                return ResourceManager.GetString("fdDirectoryMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        internal static string fdExisting {
            get {
                return ResourceManager.GetString("fdExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fdFile {
            get {
                return ResourceManager.GetString("fdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists with that name.
        /// </summary>
        internal static string fdFileAlreadyExistsFeedback {
            get {
                return ResourceManager.GetString("fdFileAlreadyExistsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing file.
        /// </summary>
        internal static string fdFileMustExistFeedback {
            get {
                return ResourceManager.GetString("fdFileMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string fdFilename {
            get {
                return ResourceManager.GetString("fdFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing file or directory.
        /// </summary>
        internal static string fdFileOrDirectoryMustExistFeedback {
            get {
                return ResourceManager.GetString("fdFileOrDirectoryMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string fdModified {
            get {
                return ResourceManager.GetString("fdModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Failed.
        /// </summary>
        internal static string fdNewFailed {
            get {
                return ResourceManager.GetString("fdNewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string fdNewTitle {
            get {
                return ResourceManager.GetString("fdNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string fdOpen {
            get {
                return ResourceManager.GetString("fdOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Path.
        /// </summary>
        internal static string fdPathCaption {
            get {
                return ResourceManager.GetString("fdPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Failed.
        /// </summary>
        internal static string fdRenameFailedTitle {
            get {
                return ResourceManager.GetString("fdRenameFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string fdRenamePrompt {
            get {
                return ResourceManager.GetString("fdRenamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string fdRenameTitle {
            get {
                return ResourceManager.GetString("fdRenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string fdSave {
            get {
                return ResourceManager.GetString("fdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string fdSaveAs {
            get {
                return ResourceManager.GetString("fdSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search.
        /// </summary>
        internal static string fdSearchCaption {
            get {
                return ResourceManager.GetString("fdSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string fdSelectFolder {
            get {
                return ResourceManager.GetString("fdSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mixed.
        /// </summary>
        internal static string fdSelectMixed {
            get {
                return ResourceManager.GetString("fdSelectMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string fdSize {
            get {
                return ResourceManager.GetString("fdSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string fdType {
            get {
                return ResourceManager.GetString("fdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file type.
        /// </summary>
        internal static string fdWrongFileTypeFeedback {
            get {
                return ResourceManager.GetString("fdWrongFileTypeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Back.
        /// </summary>
        internal static string wzBack {
            get {
                return ResourceManager.GetString("wzBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi_nish.
        /// </summary>
        internal static string wzFinish {
            get {
                return ResourceManager.GetString("wzFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next....
        /// </summary>
        internal static string wzNext {
            get {
                return ResourceManager.GetString("wzNext", resourceCulture);
            }
        }
    }
}
