//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O_pen.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _as.
        /// </summary>
        internal static string btnSaveAs {
            get {
                return ResourceManager.GetString("btnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Code_point.
        /// </summary>
        internal static string charMapCopyCP {
            get {
                return ResourceManager.GetString("charMapCopyCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _Glyph.
        /// </summary>
        internal static string charMapCopyGlyph {
            get {
                return ResourceManager.GetString("charMapCopyGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Codepoint Information.
        /// </summary>
        internal static string charMapCPInfoDlgTitle {
            get {
                return ResourceManager.GetString("charMapCPInfoDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codepoint Information from.
        /// </summary>
        internal static string charMapInfoDlgInfoLabel {
            get {
                return ResourceManager.GetString("charMapInfoDlgInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string cmd_Copy {
            get {
                return ResourceManager.GetString("cmd.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string cmd_Copy_Help {
            get {
                return ResourceManager.GetString("cmd.Copy.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        internal static string cmd_Cut {
            get {
                return ResourceManager.GetString("cmd.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut to clipboard.
        /// </summary>
        internal static string cmd_Cut_Help {
            get {
                return ResourceManager.GetString("cmd.Cut.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New file.
        /// </summary>
        internal static string cmd_New {
            get {
                return ResourceManager.GetString("cmd.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string cmd_New_Help {
            get {
                return ResourceManager.GetString("cmd.New.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        internal static string cmd_Open {
            get {
                return ResourceManager.GetString("cmd.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file.
        /// </summary>
        internal static string cmd_Open_Help {
            get {
                return ResourceManager.GetString("cmd.Open.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        internal static string cmd_Paste {
            get {
                return ResourceManager.GetString("cmd.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        internal static string cmd_Paste_Help {
            get {
                return ResourceManager.GetString("cmd.Paste.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string cmd_Quit {
            get {
                return ResourceManager.GetString("cmd.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cmd_Quit_Help {
            get {
                return ResourceManager.GetString("cmd.Quit.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string cmd_Save {
            get {
                return ResourceManager.GetString("cmd.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string cmd_Save_Help {
            get {
                return ResourceManager.GetString("cmd.Save.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        internal static string cmd_SaveAs {
            get {
                return ResourceManager.GetString("cmd.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as.
        /// </summary>
        internal static string cmd_SaveAs_Help {
            get {
                return ResourceManager.GetString("cmd.SaveAs.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select all.
        /// </summary>
        internal static string cmd_SelectAll {
            get {
                return ResourceManager.GetString("cmd.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string cmd_SelectAll_Help {
            get {
                return ResourceManager.GetString("cmd.SelectAll.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_lors.
        /// </summary>
        internal static string ctxColors {
            get {
                return ResourceManager.GetString("ctxColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string ctxCopy {
            get {
                return ResourceManager.GetString("ctxCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        internal static string ctxCut {
            get {
                return ResourceManager.GetString("ctxCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete All.
        /// </summary>
        internal static string ctxDeleteAll {
            get {
                return ResourceManager.GetString("ctxDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        internal static string ctxPaste {
            get {
                return ResourceManager.GetString("ctxPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        internal static string ctxRedo {
            get {
                return ResourceManager.GetString("ctxRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select All.
        /// </summary>
        internal static string ctxSelectAll {
            get {
                return ResourceManager.GetString("ctxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        internal static string ctxUndo {
            get {
                return ResourceManager.GetString("ctxUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Picker.
        /// </summary>
        internal static string dpTitle {
            get {
                return ResourceManager.GetString("dpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed getting.
        /// </summary>
        internal static string failedGetting {
            get {
                return ResourceManager.GetString("failedGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Files.
        /// </summary>
        internal static string fdAnyFiles {
            get {
                return ResourceManager.GetString("fdAnyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        internal static string fdCtxDelete {
            get {
                return ResourceManager.GetString("fdCtxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide {0}.
        /// </summary>
        internal static string fdCtxHide {
            get {
                return ResourceManager.GetString("fdCtxHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        internal static string fdCtxNew {
            get {
                return ResourceManager.GetString("fdCtxNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        internal static string fdCtxRename {
            get {
                return ResourceManager.GetString("fdCtxRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort {0} ASC.
        /// </summary>
        internal static string fdCtxSortAsc {
            get {
                return ResourceManager.GetString("fdCtxSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort {0} DESC.
        /// </summary>
        internal static string fdCtxSortDesc {
            get {
                return ResourceManager.GetString("fdCtxSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;? This operation is permanent.
        /// </summary>
        internal static string fdDeleteBody {
            get {
                return ResourceManager.GetString("fdDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string fdDeleteFailedTitle {
            get {
                return ResourceManager.GetString("fdDeleteFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string fdDeleteTitle {
            get {
                return ResourceManager.GetString("fdDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string fdDirectory {
            get {
                return ResourceManager.GetString("fdDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already exists with that name.
        /// </summary>
        internal static string fdDirectoryAlreadyExistsFeedback {
            get {
                return ResourceManager.GetString("fdDirectoryAlreadyExistsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing directory.
        /// </summary>
        internal static string fdDirectoryMustExistFeedback {
            get {
                return ResourceManager.GetString("fdDirectoryMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        internal static string fdExisting {
            get {
                return ResourceManager.GetString("fdExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fdFile {
            get {
                return ResourceManager.GetString("fdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists with that name.
        /// </summary>
        internal static string fdFileAlreadyExistsFeedback {
            get {
                return ResourceManager.GetString("fdFileAlreadyExistsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing file.
        /// </summary>
        internal static string fdFileMustExistFeedback {
            get {
                return ResourceManager.GetString("fdFileMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string fdFilename {
            get {
                return ResourceManager.GetString("fdFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select an existing file or directory.
        /// </summary>
        internal static string fdFileOrDirectoryMustExistFeedback {
            get {
                return ResourceManager.GetString("fdFileOrDirectoryMustExistFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string fdModified {
            get {
                return ResourceManager.GetString("fdModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Failed.
        /// </summary>
        internal static string fdNewFailed {
            get {
                return ResourceManager.GetString("fdNewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string fdNewTitle {
            get {
                return ResourceManager.GetString("fdNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string fdOpen {
            get {
                return ResourceManager.GetString("fdOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Path.
        /// </summary>
        internal static string fdPathCaption {
            get {
                return ResourceManager.GetString("fdPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Failed.
        /// </summary>
        internal static string fdRenameFailedTitle {
            get {
                return ResourceManager.GetString("fdRenameFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string fdRenamePrompt {
            get {
                return ResourceManager.GetString("fdRenamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string fdRenameTitle {
            get {
                return ResourceManager.GetString("fdRenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string fdSave {
            get {
                return ResourceManager.GetString("fdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string fdSaveAs {
            get {
                return ResourceManager.GetString("fdSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search.
        /// </summary>
        internal static string fdSearchCaption {
            get {
                return ResourceManager.GetString("fdSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string fdSelectFolder {
            get {
                return ResourceManager.GetString("fdSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mixed.
        /// </summary>
        internal static string fdSelectMixed {
            get {
                return ResourceManager.GetString("fdSelectMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string fdSize {
            get {
                return ResourceManager.GetString("fdSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string fdType {
            get {
                return ResourceManager.GetString("fdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file type.
        /// </summary>
        internal static string fdWrongFileTypeFeedback {
            get {
                return ResourceManager.GetString("fdWrongFileTypeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Back.
        /// </summary>
        internal static string wzBack {
            get {
                return ResourceManager.GetString("wzBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi_nish.
        /// </summary>
        internal static string wzFinish {
            get {
                return ResourceManager.GetString("wzFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next....
        /// </summary>
        internal static string wzNext {
            get {
                return ResourceManager.GetString("wzNext", resourceCulture);
            }
        }
    }
}
