using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Terminal.Gui.Analyzers.Internal;

/// <summary>
///     Incremental source generator that produces high-performance enum extension methods
///     (<c>AsInt32</c>, <c>AsUInt32</c>, <c>FastIsDefined</c>, and <c>FastHasFlags</c> for
///     <see cref="System.FlagsAttribute"/> enums) for every public enum in the compilation.
/// </summary>
[Generator (LanguageNames.CSharp)]
public sealed class EnumExtensionMethodsGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize (IncrementalGeneratorInitializationContext context)
    {
        // Collect all enum declarations that are public and in a namespace.
        IncrementalValuesProvider<EnumInfo?> enumInfos = context.SyntaxProvider
                                                                .CreateSyntaxProvider (static (node, _) => node is EnumDeclarationSyntax,
                                                                                       static (ctx, ct) => GetEnumInfo (ctx, ct))
                                                                .Where (static info => info is { });

        context.RegisterSourceOutput (enumInfos, static (spc, enumInfo) => Execute (spc, enumInfo!));
    }

    private static EnumInfo? GetEnumInfo (GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested ();

        if (context.Node is not EnumDeclarationSyntax enumDecl)
        {
            return null;
        }

        var symbol = context.SemanticModel.GetDeclaredSymbol (enumDecl, cancellationToken) as INamedTypeSymbol;

        if (symbol is null)
        {
            return null;
        }

        // Only generate for public enums.
        if (symbol.DeclaredAccessibility != Accessibility.Public)
        {
            return null;
        }

        // Skip enums nested inside other types (classes, structs, etc.).
        // Unsafe.As reinterpret casts require the struct to be at least 4 bytes,
        // and nested types need special qualification the generated code does not produce.
        if (symbol.ContainingType is { })
        {
            return null;
        }

        // Only support enums in a namespace.
        if (symbol.ContainingNamespace is null or { IsGlobalNamespace: true })
        {
            return null;
        }

        // Only generate for int and uint backed enums.
        // Unsafe.As<TEnum, int/uint> requires the enum to be exactly 4 bytes.
        string? underlyingTypeName = symbol.EnumUnderlyingType?.SpecialType switch
                                     {
                                         SpecialType.System_Int32 => "int",
                                         SpecialType.System_UInt32 => "uint",
                                         _ => null
                                     };

        if (underlyingTypeName is null)
        {
            return null;
        }

        string enumNamespace = symbol.ContainingNamespace.ToDisplayString ();
        string enumName = symbol.Name;

        bool hasFlags = symbol.GetAttributes ().Any (static a => a.AttributeClass?.ToDisplayString () == "System.FlagsAttribute");

        // Collect member values (deduplicate).
        HashSet<int> memberValues = new ();

        foreach (ISymbol member in symbol.GetMembers ())
        {
            if (member is not IFieldSymbol { HasConstantValue: true } field)
            {
                continue;
            }

            int value = field.ConstantValue switch
                        {
                            int i => i,
                            uint u => unchecked ((int)u),
                            _ => 0
                        };
            memberValues.Add (value);
        }

        return new EnumInfo (enumNamespace, enumName, underlyingTypeName, hasFlags, memberValues.OrderBy (static v => unchecked ((uint)v)).ToArray ());
    }

    private static void Execute (SourceProductionContext context, EnumInfo info)
    {
        string source = GenerateExtensionClass (info);
        context.AddSource ($"{info.Namespace}.{info.Name}Extensions.g.cs", SourceText.From (source, Encoding.UTF8));
    }

    private static string GenerateExtensionClass (EnumInfo info)
    {
        StringBuilder sb = new (2048);

        sb.AppendLine ("// <auto-generated/>");
        sb.AppendLine ("#nullable enable");
        sb.AppendLine ();
        sb.AppendLine ("using System.CodeDom.Compiler;");
        sb.AppendLine ("using System.Diagnostics;");
        sb.AppendLine ("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine ("using System.Runtime.CompilerServices;");
        sb.AppendLine ();
        sb.Append ("namespace ").Append (info.Namespace).AppendLine (";");
        sb.AppendLine ();
        sb.Append ("/// <summary>Extension methods for the <see cref=\"").Append (info.Name).AppendLine ("\"/> <see langword=\"enum\"/> type.</summary>");
        sb.AppendLine ("[GeneratedCode (\"Terminal.Gui.Analyzers.Internal\", \"1.0\")]");
        sb.Append ("public static partial class ").Append (info.Name).AppendLine ("Extensions");
        sb.AppendLine ("{");

        // AsInt32
        sb.AppendLine ("    /// <summary>");

        sb.Append ("    ///     Directly converts this <see cref=\"")
          .Append (info.Name)
          .AppendLine ("\"/> value to an <see langword=\"int\"/> value with the same");
        sb.AppendLine ("    ///     binary representation.");
        sb.AppendLine ("    /// </summary>");
        sb.AppendLine ("    /// <remarks>NO VALIDATION IS PERFORMED!</remarks>");
        sb.AppendLine ("    [MethodImpl (MethodImplOptions.AggressiveInlining)]");
        sb.Append ("    public static int AsInt32 (this ").Append (info.Name).Append (" e) => Unsafe.As<").Append (info.Name).AppendLine (", int> (ref e);");
        sb.AppendLine ();

        // AsUInt32
        sb.AppendLine ("    /// <summary>");

        sb.Append ("    ///     Directly converts this <see cref=\"")
          .Append (info.Name)
          .AppendLine ("\"/> value to a <see langword=\"uint\"/> value with the same");
        sb.AppendLine ("    ///     binary representation.");
        sb.AppendLine ("    /// </summary>");
        sb.AppendLine ("    /// <remarks>NO VALIDATION IS PERFORMED!</remarks>");
        sb.AppendLine ("    [MethodImpl (MethodImplOptions.AggressiveInlining)]");
        sb.Append ("    public static uint AsUInt32 (this ").Append (info.Name).Append (" e) => Unsafe.As<").Append (info.Name).AppendLine (", uint> (ref e);");

        // FastHasFlags (for [Flags] enums only)
        if (info.HasFlags)
        {
            sb.AppendLine ();

            // Overload 1: same enum type
            sb.AppendLine ("    /// <summary>");
            sb.Append ("    ///     Determines if the specified flags are set in the current value of this").AppendLine ();
            sb.Append ("    ///     <see cref=\"").Append (info.Name).AppendLine ("\"/>.");
            sb.AppendLine ("    /// </summary>");
            sb.AppendLine ("    /// <remarks>NO VALIDATION IS PERFORMED!</remarks>");
            sb.AppendLine ("    /// <returns>");
            sb.Append ("    ///     True, if all flags present in <paramref name=\"checkFlags\"/> are also present in the current value of the").AppendLine ();
            sb.Append ("    ///     <see cref=\"").Append (info.Name).AppendLine ("\"/>.<br/>Otherwise false.");
            sb.AppendLine ("    /// </returns>");
            sb.AppendLine ("    [MethodImpl (MethodImplOptions.AggressiveInlining)]");
            sb.Append ("    public static bool FastHasFlags (this ").Append (info.Name).Append (" e, ").Append (info.Name).AppendLine (" checkFlags)");
            sb.AppendLine ("    {");
            sb.Append ("        ref uint enumCurrentValueRef = ref Unsafe.As<").Append (info.Name).AppendLine (", uint> (ref e);");
            sb.Append ("        ref uint checkFlagsValueRef = ref Unsafe.As<").Append (info.Name).AppendLine (", uint> (ref checkFlags);");
            sb.AppendLine ();
            sb.AppendLine ("        return (enumCurrentValueRef & checkFlagsValueRef) == checkFlagsValueRef;");
            sb.AppendLine ("    }");

            sb.AppendLine ();

            // Overload 2: int mask
            sb.AppendLine ("    /// <summary>");
            sb.Append ("    ///     Determines if the specified mask bits are set in the current value of this").AppendLine ();
            sb.Append ("    ///     <see cref=\"").Append (info.Name).AppendLine ("\"/>.");
            sb.AppendLine ("    /// </summary>");

            sb.Append ("    /// <param name=\"e\">The <see cref=\"")
              .Append (info.Name)
              .AppendLine ("\"/> value to check against the <paramref name=\"mask\"/> value.</param>");
            sb.AppendLine ("    /// <param name=\"mask\">A mask to apply to the current value.</param>");
            sb.AppendLine ("    /// <returns>");
            sb.Append ("    ///     True, if all bits set to 1 in the mask are also set to 1 in the current value of the").AppendLine ();
            sb.Append ("    ///     <see cref=\"").Append (info.Name).AppendLine ("\"/>.<br/>Otherwise false.");
            sb.AppendLine ("    /// </returns>");
            sb.AppendLine ("    /// <remarks>NO VALIDATION IS PERFORMED!</remarks>");
            sb.AppendLine ("    [MethodImpl (MethodImplOptions.AggressiveInlining)]");
            sb.Append ("    public static bool FastHasFlags (this ").Append (info.Name).Append (" e, ").Append (info.UnderlyingKeyword).AppendLine (" mask)");
            sb.AppendLine ("    {");

            sb.Append ("        ref ")
              .Append (info.UnderlyingKeyword)
              .Append (" enumCurrentValueRef = ref Unsafe.As<")
              .Append (info.Name)
              .Append (", ")
              .Append (info.UnderlyingKeyword)
              .AppendLine ("> (ref e);");
            sb.AppendLine ();
            sb.AppendLine ("        return (enumCurrentValueRef & mask) == mask;");
            sb.AppendLine ("    }");
        }

        // FastIsDefined
        sb.AppendLine ();
        sb.AppendLine ("    /// <summary>");
        sb.Append ("    ///     Determines if the specified <see langword=\"int\"/> value is explicitly defined as a named value of the").AppendLine ();
        sb.Append ("    ///     <see cref=\"").Append (info.Name).AppendLine ("\"/> <see langword=\"enum\"/> type.");
        sb.AppendLine ("    /// </summary>");
        sb.AppendLine ("    /// <remarks>");
        sb.AppendLine ("    ///     Only explicitly named values return true, as with IsDefined. Combined valid flag values of flags enums which are");
        sb.AppendLine ("    ///     not explicitly named will return false.");
        sb.AppendLine ("    /// </remarks>");
        sb.Append ("    public static bool FastIsDefined (this ").Append (info.Name).AppendLine (" _, int value)");
        sb.AppendLine ("    {");
        sb.AppendLine ("        return value switch");
        sb.AppendLine ("               {");

        foreach (int value in info.MemberValues)
        {
            sb.Append ("                   ").Append (value).AppendLine (" => true,");
        }

        sb.AppendLine ("                   _ => false");
        sb.AppendLine ("               };");
        sb.AppendLine ("    }");

        sb.AppendLine ("}");

        return sb.ToString ();
    }

    private sealed class EnumInfo (string ns, string name, string underlyingKeyword, bool hasFlags, int [] memberValues)
    {
        public string Namespace { get; } = ns;
        public string Name { get; } = name;
        public string UnderlyingKeyword { get; } = underlyingKeyword;
        public bool HasFlags { get; } = hasFlags;
        public int [] MemberValues { get; } = memberValues;
    }
}
