namespace Terminal.Gui.Drivers;

/// <summary>
///     Kitty keyboard progressive enhancement flags.
///     These correspond to the bit flags defined in the kitty keyboard protocol specification.
/// </summary>
/// <remarks>
///     See <see href="https://sw.kovidgoyal.net/kitty/keyboard-protocol/#progressive-enhancement"/>.
/// </remarks>
[Flags]
public enum KittyKeyboardFlags
{
    /// <summary>
    ///     No flags set.
    /// </summary>
    None = 0,

    /// <summary>
    ///     Disambiguate escape codes (flag 0b1).
    ///     Encodes keys unambiguously as CSI u sequences instead of legacy escape sequences.
    /// </summary>
    DisambiguateEscapeCodes = 1,

    /// <summary>
    ///     Report event types — press, repeat, release (flag 0b10).
    ///     Enables the terminal to report key release and repeat events in addition to key press.
    /// </summary>
    ReportEventTypes = 2,

    /// <summary>
    ///     Report alternate keys (flag 0b100).
    ///     Enables the terminal to report alternate key values (e.g., shifted key, base layout key).
    /// </summary>
    ReportAlternateKeys = 4,

    /// <summary>
    ///     Report all keys as escape codes (flag 0b1000).
    ///     Enables the terminal to report standalone modifier key events (e.g., pressing Shift alone).
    /// </summary>
    ReportAllKeysAsEscapeCodes = 8,

    /// <summary>
    ///     Report associated text (flag 0b10000).
    ///     Enables the terminal to report the text generated by a key event.
    /// </summary>
    ReportAssociatedText = 16
}
