using Terminal.Gui;

namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "CenteredWindowInsideWindow", Description: "Centered Window Inside Window")]
	[ScenarioCategory ("Controls")]
	public class CenteredWindowInsideWindow : Scenario {
		public override void Init (ColorScheme colorScheme)
		{
			Application.Init ();

			Application.Run<ParentWindowClass> ();
			Application.Shutdown ();
		}

		public override void Run ()
		{
		}
	}


	//------------------------------------------------------------------------------

	//  <auto-generated>
	//      This code was generated by:
	//        TerminalGuiDesigner v1.0.24.0
	//      You can make changes to this file and they will not be overwritten when saving.
	//  </auto-generated>
	// -----------------------------------------------------------------------------

	public partial class ParentWindowClass {

		private ChildWindowClass? _childWindow;
		public ParentWindowClass ()
		{
			InitializeComponent ();
			// MenuBar
			createChildMenuItem.CanExecute = CanExecuteCreateChildWindow;
			createChildMenuItem.Action = CreateChildWindow;
			centerChildMenuItem.CanExecute = CanExecuteCenterChildWindow;
			centerChildMenuItem.Action = CenterChildWindow;
			hideChildMenuItem.CanExecute = CanExecuteHideChildWindow;
			hideChildMenuItem.Action = HideChildWindow;
			// StatusBar
			createChildStatusItem.CanExecute = CanExecuteCreateChildWindow;
			createChildStatusItem.Action = CreateChildWindow;
			centerChildStatusItem.CanExecute = CanExecuteCenterChildWindow;
			centerChildStatusItem.Action = CenterChildWindow;
			hideChildStatusItem.CanExecute = CanExecuteHideChildWindow;
			hideChildStatusItem.Action = HideChildWindow;

			KeyPress += ParentWindowClass_KeyPress;
		}

		private void ParentWindowClass_KeyPress (KeyEventEventArgs obj)
		{
			switch (obj.KeyEvent.Key) {
			case Key.F8:
				menuBar.Visible = !menuBar.Visible;
				obj.Handled = true;
				break;
			case Key.F10:
				statusBar.Visible = !statusBar.Visible;
				obj.Handled = true;
				break;
			}
		}

		private bool CanExecuteCreateChildWindow () => _childWindow == null;

		private void CreateChildWindow ()
		{
			_childWindow ??= new ChildWindowClass ();
			Add (_childWindow);
		}

		private bool CanExecuteCenterChildWindow () => _childWindow != null && _childWindow.Visible;

		private void CenterChildWindow ()
		{
			_childWindow.X = Pos.Center ();
			_childWindow.Y = Pos.Center ();
			_childWindow.SetNeedsDisplay ();
		}

		private bool CanExecuteHideChildWindow () => _childWindow != null;

		private void HideChildWindow ()
		{
			if (_childWindow.Visible) {
				_childWindow.Visible = false;
				// MenuBar
				hideChildMenuItem.Title = "Un_Hide Child";
				// StatusBar
				hideChildStatusItem.Title = "~CTRL-F7~ UnHide Child";
			} else {
				_childWindow.Visible = true;
				// MenuBar
				hideChildMenuItem.Title = "_Hide Child";
				// StatusBar
				hideChildStatusItem.Title = "~CTRL-F7~ Hide Child";
			}
		}
	}

	//------------------------------------------------------------------------------

	//  <auto-generated>
	//      This code was generated by:
	//        TerminalGuiDesigner v1.0.24.0
	//      Changes to this file may cause incorrect behavior and will be lost if
	//      the code is regenerated.
	//  </auto-generated>
	// -----------------------------------------------------------------------------

	public partial class ParentWindowClass : Terminal.Gui.Window {

		private Terminal.Gui.MenuBar menuBar;

		private Terminal.Gui.MenuBarItem childMenu;

		private Terminal.Gui.MenuItem createChildMenuItem;
		private Terminal.Gui.MenuItem centerChildMenuItem;
		private Terminal.Gui.MenuItem hideChildMenuItem;

		private Terminal.Gui.StatusBar statusBar;

		private Terminal.Gui.StatusItem createChildStatusItem;
		private Terminal.Gui.StatusItem centerChildStatusItem;
		private Terminal.Gui.StatusItem hideChildStatusItem;

		private void InitializeComponent ()
		{
			this.menuBar = new Terminal.Gui.MenuBar ();
			this.Width = Dim.Fill (0);
			this.Height = Dim.Fill (0);
			this.X = 0;
			this.Y = 0;
			this.Modal = false;
			this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
			this.Border.BorderBrush = Terminal.Gui.Color.White;
			this.Border.Effect3D = false;
			this.Border.Effect3DBrush = null;
			this.Border.DrawMarginFrame = true;
			this.TextAlignment = Terminal.Gui.TextAlignment.Left;
			this.Title = "Parent Window (Press F8 to Hide/Show MenuBar)(Press F10 to Hide/Show StatusBar)";
			this.menuBar.Width = Dim.Fill (0);
			this.menuBar.Height = 1;
			this.menuBar.X = 0;
			this.menuBar.Y = 0;
			this.menuBar.Data = "menuBar";
			this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
			this.childMenu = new Terminal.Gui.MenuBarItem ();
			this.childMenu.Title = "Ch_ild";
			this.createChildMenuItem = new Terminal.Gui.MenuItem ();
			this.createChildMenuItem.Title = "_Create Child";
			this.createChildMenuItem.Data = "createChildMenuItem";
			this.menuBar.Menus = new Terminal.Gui.MenuBarItem [] {
					this.childMenu};
			this.centerChildMenuItem = new Terminal.Gui.MenuItem ();
			this.centerChildMenuItem.Title = "C_enter Child";
			this.centerChildMenuItem.Data = "centerChildMenuItem";
			this.centerChildMenuItem.CanExecute = () => false;
			this.hideChildMenuItem = new Terminal.Gui.MenuItem ();
			this.hideChildMenuItem.Title = "_Hide Child";
			this.hideChildMenuItem.Data = "hideChildMenuItem";
			this.hideChildMenuItem.CanExecute = () => false;
			this.childMenu.Children = new Terminal.Gui.MenuItem [] {
					this.createChildMenuItem, this.centerChildMenuItem, this.hideChildMenuItem};
			this.Add (this.menuBar);
			this.statusBar = new Terminal.Gui.StatusBar ();
			this.statusBar.Width = Dim.Fill ();
			this.statusBar.Height = 1;
			this.statusBar.X = 0;
			this.statusBar.Y = Pos.AnchorEnd (1);
			this.statusBar.Data = "statusBar";
			this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
			this.createChildStatusItem = new Terminal.Gui.StatusItem (Key.F5 | Key.CtrlMask, "~CTRL-F5~ Create Child", null);
			this.createChildStatusItem.Data = "createChildStatusItem";
			this.centerChildStatusItem = new Terminal.Gui.StatusItem (Key.F6 | Key.CtrlMask, "~CTRL-F6~ Center Child", null);
			this.centerChildStatusItem.Data = "centerChildStatusItem";
			this.hideChildStatusItem = new Terminal.Gui.StatusItem (Key.F7 | Key.CtrlMask, "~CTRL-F7~ Hide Child", null);
			this.hideChildStatusItem.Data = "hideChildStatusItem";
			this.statusBar.Items = new StatusItem [] {
					this.createChildStatusItem, this.centerChildStatusItem, this.hideChildStatusItem};
			this.Add (statusBar);
		}
	}

	//------------------------------------------------------------------------------

	//  <auto-generated>
	//      This code was generated by:
	//        TerminalGuiDesigner v1.0.24.0
	//      You can make changes to this file and they will not be overwritten when saving.
	//  </auto-generated>
	// -----------------------------------------------------------------------------

	public partial class ChildWindowClass {

		public ChildWindowClass ()
		{
			InitializeComponent ();
			this.button1.Clicked += Button1_Clicked;
		}

		private void Button1_Clicked ()
		{
			Terminal.Gui.MessageBox.Query ("Press Me", "I hope you like the child window behavior!", "Ok");
		}
	}


	//------------------------------------------------------------------------------

	//  <auto-generated>
	//      This code was generated by:
	//        TerminalGuiDesigner v1.0.24.0
	//      Changes to this file may cause incorrect behavior and will be lost if
	//      the code is regenerated.
	//  </auto-generated>
	// -----------------------------------------------------------------------------

	public partial class ChildWindowClass : Terminal.Gui.Window {

		private Terminal.Gui.Button button1;

		private void InitializeComponent ()
		{
			this.Width = 80;
			this.Height = 16;
			this.X = Pos.Center ();
			this.Y = Pos.Center ();
			this.Modal = false;
			this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
			this.Border.BorderBrush = Terminal.Gui.Color.White;
			this.Border.Effect3D = false;
			this.Border.Effect3DBrush = null;
			this.Border.DrawMarginFrame = true;
			this.TextAlignment = Terminal.Gui.TextAlignment.Left;
			this.Title = "Child Window";
			this.button1 = new Terminal.Gui.Button ();
			this.button1.X = Pos.Center ();
			this.button1.Y = Pos.Center ();
			this.button1.Text = "Press Me";
			this.Add (this.button1);
		}
	}
}