# Script to generate views.md from API documentation using tuirec for GIF recordings
param(
    [string]$ApiPath = "api",
    [string]$OutputPath = "docs/views.md",
    [string]$ImagePath = "images/views",
    [switch]$Debug,
    [switch]$SkipGifs
)

# Ensure we're in the correct directory (docfx root)
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$rootPath = Split-Path -Parent $scriptPath
Set-Location $rootPath

Write-Host "Working directory: $(Get-Location)"
Write-Host "Looking for view files in: $ApiPath"

# Create images output directory
if (-not (Test-Path $ImagePath)) {
    New-Item -ItemType Directory -Path $ImagePath -Force | Out-Null
}

# Build OutputView once
Write-Host "Building OutputView..." -ForegroundColor Cyan
dotnet build scripts/OutputView -c Release --verbosity quiet
if ($LASTEXITCODE -ne 0) {
    Write-Host "Failed to build OutputView!" -ForegroundColor Red
    exit 1
}
$outputViewDll = "scripts/OutputView/bin/Release/net10.0/OutputView.dll"

# Get all .yml files in the API directory that are Views
if ($Debug) {
    $viewFiles = Get-ChildItem -Path $ApiPath -Filter "Terminal.Gui.Views.HexView.yml"
    Write-Host "DEBUG MODE: Only processing" $viewFiles -ForegroundColor Cyan
} else {
    $viewFiles = Get-ChildItem -Path $ApiPath -Filter "Terminal.Gui.Views.*.yml"
}
Write-Host "Found $($viewFiles.Count) view files"

# Start building the markdown content
$content = @"
<!-- 
This file is automatically generated from the API documentation and the OutputView tool.
GIFs are recorded using tuirec (https://github.com/gui-cs/tuirec).
Run: cd docfx && ./scripts/generate-views-doc.ps1
-->
# Terminal Gui's Built-in Views

*Terminal.Gui* provides the following set of built-in views and controls for building terminal user interfaces:


"@

# Process each view file
$views = @()
foreach ($file in $viewFiles) {
    try {
        $yml = Get-Content $file.FullName -Raw | ConvertFrom-Yaml
        
        # Check if this is actually a View type
        $isView = $false
        if ($yml.items[0].inheritance) {
            $isView = $yml.items[0].inheritance -contains "Terminal.Gui.ViewBase.View"
        }
        
        if (-not $isView) {
            continue
        }
        
        # Extract the view name and description
        $name = $file.BaseName -replace "^Terminal\.Gui\.Views\.", ""
        
        # Handle generic types
        if ($name -match "(.+)-(\d+)$") {
            $name = "$($matches[1])\<T\>"
        }
        
        $description = $yml.items[0].summary
        
        # Clean up the description
        $description = $description -replace "`r`n", " "
        $description = $description -replace "\s+", " "
        $description = $description.Trim()
        $description = $description -replace '([^a-zA-Z0-9]+)\1+', '$1'
        $description = $description -replace '<p>|</p>', ''
        $description = $description -replace '<a href="[^"]+">([^<]+)</a>', '$1'
        $description = $description -replace '<xref href="([^"]+)"[^>]*>([^<]+)</xref>', '[$2](xref:$1)'
        $description = $description -replace '<see cref="([^"]+)"/>', '<xref:$1>'
        $description = $description -replace '<c>([^<]+)</c>', '`$1`'
        $description = $description -replace '<code>([^<]*)</code>', '`$1`'
        $description = $description -replace '<xref href="([^"]+)"[^>]*></xref>', '<xref:$1>'
        $description = $description -replace '\[Terminal\.Gui\.Views\.([^\]]+)\]', '[$1]'
        $description = $description -replace '\[Terminal\.Gui\.ViewBase\.([^\]]+)\]', '[$1]'
        $description = $description -replace '\[Terminal\.Gui\.Drawing\.([^\]]+)\]', '[$1]'
        $description = $description -replace '\[Terminal\.Gui\.Input\.([^\]]+)\]', '[$1]'
        $description = $description -replace '\[System\.([^\]]+)\]', '[$1]'
        
        # Record GIF with tuirec
        $gifOutput = ""
        $viewNameClean = $file.BaseName -replace "^Terminal\.Gui\.Views\.", ""
        
        if (-not $SkipGifs) {
            try {
                # Query the view's demo keystrokes
                Write-Host "  Querying keystrokes for $viewNameClean..." -ForegroundColor Gray
                $ks = & dotnet $outputViewDll --view=$viewNameClean --keystrokes 2>$null
                $ks = $ks.Trim()
                $isStatic = [string]::IsNullOrEmpty($ks)
                
                if ($isStatic) {
                    # No demo keystrokes — click the center to trigger any interactive
                    # element (menus, popovers) and produce a visual change for --trim
                    $ks = "wait:1500,click:40:10,wait:1000"
                }
                
                # Append a pause (so final state is visible) then Escape to quit
                $ks = "$ks,wait:500,Escape"
                
                $gifFile = Join-Path $ImagePath "$viewNameClean.gif"
                
                Write-Host "  Recording $viewNameClean with tuirec..." -ForegroundColor Cyan
                Write-Host "    Keystrokes: $ks" -ForegroundColor Gray
                
                # Always use --trim to remove preroll/postroll (v0.4.2+)
                tuirec record `
                    --binary dotnet `
                    --args "$outputViewDll,--view=$viewNameClean,--live,--frame" `
                    --name $viewNameClean `
                    --title $viewNameClean `
                    --keystrokes $ks `
                    --startup-delay 0 `
                    --drain 1000 `
                    --trim `
                    --mouse-pointer none `
                    --cols 80 --rows 20 `
                    --output $gifFile `
                    --verbosity quiet
                
                # Retry without trim if validation failed (should not happen now that
                # OutputView writes a clear-screen baseline frame before rendering)
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "    WARNING: --trim failed (exit $LASTEXITCODE), retrying without trim..." -ForegroundColor Yellow
                    tuirec record `
                        --binary dotnet `
                        --args "$outputViewDll,--view=$viewNameClean,--live,--frame" `
                        --name $viewNameClean `
                        --title $viewNameClean `
                        --keystrokes $ks `
                        --startup-delay 0 `
                        --drain 1000 `
                        --trim=false `
                        --mouse-pointer none `
                        --cols 80 --rows 20 `
                        --output $gifFile `
                        --verbosity quiet
                }
                
                if ($LASTEXITCODE -eq 0 -and (Test-Path $gifFile)) {
                    $gifSize = (Get-Item $gifFile).Length
                    Write-Host "    OK ($gifSize bytes)" -ForegroundColor Green
                    $gifOutput = "`n![${viewNameClean}](../images/views/${viewNameClean}.gif)`n"
                } else {
                    Write-Host "    FAILED (exit code $LASTEXITCODE)" -ForegroundColor Red
                }
            }
            catch {
                Write-Host "    Error recording $viewNameClean : $_" -ForegroundColor Red
            }
        }
        
        # Build xref UID
        $xrefUid = $file.BaseName -replace '-(\d+)$', '`$1'

        Write-Host "Found view: $name"
        $views += "## [$name](xref:$xrefUid)`n`n$description`n`n$gifOutput`n"
    }
    catch {
        Write-Host "  Error processing $($file.Name): $_" -ForegroundColor Red
    }
}

Write-Host "Sorting views..."
$views = $views | Sort-Object

Write-Host "Generating markdown..."
$content += "`n" + ($views -join "`n")

Write-Host "Writing to $OutputPath..."
$content | Set-Content -Path $OutputPath -NoNewline

Write-Host "Generated $OutputPath successfully" -ForegroundColor Green