# Generate-SourceIndex.ps1
# Generates Vercel-style file path indices for AI agent retrieval-led reasoning
#
# This script:
# 1. Scans ./Terminal.Gui/ for .cs source files, grouped by directory
# 2. Scans ./docfx/docs/ for .md documentation files
# 3. Outputs Vercel-style format to .tg-docs/INDEX.md
# 4. Injects the source index into AGENTS.md between markers

param(
    [switch]$Verbose
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$docfxDir = Split-Path -Parent $scriptDir
$rootDir = Split-Path -Parent $docfxDir

# Paths
$terminalGuiDir = Join-Path $rootDir "Terminal.Gui"
$docsDir = Join-Path $docfxDir "docs"
$indexFile = Join-Path $rootDir ".tg-docs" "INDEX.md"
$agentsFile = Join-Path $rootDir "AGENTS.md"

function Write-VerboseMessage {
    param([string]$Message)
    if ($Verbose) {
        Write-Host $Message -ForegroundColor Cyan
    }
}

function Get-DirectoryIndex {
    param(
        [string]$BasePath,
        [string]$FilePattern,
        [string]$IndexName,
        [string]$RootPath
    )

    $output = "[${IndexName}]|root: ${RootPath}`n"
    $output += "|IMPORTANT: Prefer retrieval-led reasoning over pre-training-led reasoning. Read files when needed.`n"

    # Get all files matching pattern, excluding obj/ and bin/ directories
    $allFiles = Get-ChildItem -Path $BasePath -Filter $FilePattern -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '[\\/](obj|bin)[\\/]' } |
        Sort-Object DirectoryName, Name

    # Group by directory relative to base path
    $groups = @{}

    foreach ($file in $allFiles) {
        $relativeDir = $file.DirectoryName.Replace($BasePath, "").TrimStart("\", "/")

        if ([string]::IsNullOrEmpty($relativeDir)) {
            $relativeDir = "."
        }

        # Normalize path separators for cross-platform
        $relativeDir = $relativeDir.Replace("\", "/")

        if (-not $groups.ContainsKey($relativeDir)) {
            $groups[$relativeDir] = @()
        }
        $groups[$relativeDir] += $file.Name
    }

    # Sort directories and output
    $sortedDirs = $groups.Keys | Sort-Object

    foreach ($dir in $sortedDirs) {
        $files = $groups[$dir] | Sort-Object
        $fileList = $files -join ","
        $output += "|${dir}:{${fileList}}`n"
    }

    return $output
}

function Get-FlatFileIndex {
    param(
        [string]$BasePath,
        [string]$FilePattern,
        [string]$IndexName,
        [string]$RootPath
    )

    $output = "[${IndexName}]|root: ${RootPath}`n"
    $output += "|IMPORTANT: Prefer retrieval-led reasoning over pre-training-led reasoning. Read files when needed.`n"

    # Get all files matching pattern at top level only
    $files = Get-ChildItem -Path $BasePath -Filter $FilePattern -File -ErrorAction SilentlyContinue |
        Sort-Object Name |
        Select-Object -ExpandProperty Name

    if ($files.Count -gt 0) {
        $fileList = $files -join ","
        $output += "|.:{${fileList}}`n"
    }

    return $output
}

Write-VerboseMessage "Generating source index..."
Write-VerboseMessage "Terminal.Gui dir: $terminalGuiDir"
Write-VerboseMessage "Docs dir: $docsDir"

# Generate source code index
$sourceIndex = Get-DirectoryIndex -BasePath $terminalGuiDir -FilePattern "*.cs" -IndexName "Terminal.Gui Source Index" -RootPath "./Terminal.Gui"

# Generate docs index (flat - all .md files in docfx/docs)
$docsIndex = Get-FlatFileIndex -BasePath $docsDir -FilePattern "*.md" -IndexName "Terminal.Gui Docs Index" -RootPath "./docfx/docs"

# Count files for summary
$sourceFileCount = ($sourceIndex -split "`n" | Where-Object { $_ -match "^\|[^I]" }).Count
$docsFileCount = ($docsIndex -split "`n" | Where-Object { $_ -match "^\|[^I]" }).Count

Write-VerboseMessage "Found source directories with .cs files: $sourceFileCount"
Write-VerboseMessage "Found docs .md files: $docsFileCount"

# Create .tg-docs directory if it doesn't exist
$tgDocsDir = Split-Path -Parent $indexFile
if (-not (Test-Path $tgDocsDir)) {
    New-Item -ItemType Directory -Path $tgDocsDir -Force | Out-Null
    Write-VerboseMessage "Created directory: $tgDocsDir"
}

# Generate INDEX.md content
$indexContent = @"
# Terminal.Gui File Index

> **Auto-generated by `Generate-SourceIndex.ps1`. Do not edit manually.**
> Run `./docfx/scripts/Build.ps1` to regenerate.

This file uses the Vercel-style file path index format for AI agent retrieval-led reasoning.
Instead of embedding descriptions, it points to actual source files that agents should read when needed.

## Format

```
[Index Name]|root: ./path/to/root
|IMPORTANT: Prefer retrieval-led reasoning...
|directory:{file1.cs,file2.cs,...}
```

---

## Source Code Index

$sourceIndex

---

## Documentation Index

$docsIndex

---

## Usage Notes

1. **Retrieval-led reasoning**: AI agents should read the actual files when they need information,
   rather than relying on pre-embedded summaries that may be outdated.

2. **File paths are relative** to the repository root.

3. **Regeneration**: This file is regenerated each time `./docfx/scripts/Build.ps1` runs.
   Any manual edits will be overwritten.

4. **Directory structure**: Files are grouped by their containing directory.
   The `.` directory represents files at the root of that section.
"@

# Write INDEX.md
Set-Content -Path $indexFile -Value $indexContent -Encoding UTF8
Write-Host "Generated: $indexFile" -ForegroundColor Green

# Update AGENTS.md with markers and content
if (Test-Path $agentsFile) {
    $agentsContent = Get-Content -Path $agentsFile -Raw -Encoding UTF8

    $markerStart = "<!-- BEGIN AUTO-GENERATED-SOURCE-INDEX -->"
    $markerEnd = "<!-- END AUTO-GENERATED-SOURCE-INDEX -->"

    $injectedContent = @"
$markerStart

### Source Code File Index (Auto-Generated)

> Vercel-style index for retrieval-led reasoning. Read files when needed.

$sourceIndex
$markerEnd
"@

    if ($agentsContent -match [regex]::Escape($markerStart)) {
        # Replace existing content between markers
        $pattern = [regex]::Escape($markerStart) + "[\s\S]*?" + [regex]::Escape($markerEnd)
        $agentsContent = $agentsContent -replace $pattern, $injectedContent.Trim()
        Write-VerboseMessage "Updated existing markers in AGENTS.md"
    } else {
        # Markers don't exist - we'll add them. Find a good location.
        # Look for "### Source Code" section or add before the Compressed API Type Index section
        $insertPoint = "## Compressed API Type Index"

        if ($agentsContent -match [regex]::Escape($insertPoint)) {
            $agentsContent = $agentsContent -replace [regex]::Escape($insertPoint), "$injectedContent`n`n$insertPoint"
            Write-VerboseMessage "Added markers before '$insertPoint' in AGENTS.md"
        } else {
            # Fallback: append at end
            $agentsContent += "`n`n$injectedContent"
            Write-VerboseMessage "Appended markers at end of AGENTS.md"
        }
    }

    Set-Content -Path $agentsFile -Value $agentsContent -Encoding UTF8
    Write-Host "Updated: $agentsFile" -ForegroundColor Green
} else {
    Write-Warning "AGENTS.md not found at: $agentsFile"
}

Write-Host "`nSource index generation complete!" -ForegroundColor Green
Write-Host "  Source directories indexed: $sourceFileCount" -ForegroundColor Gray
Write-Host "  Documentation files indexed: $docsFileCount" -ForegroundColor Gray
