// Copilot

using ApplicationTests.Popover;
using UnitTests;

namespace ApplicationTests.MouseTests;

/// <summary>
///     Tests that mouse coordinate offset adjustment in inline mode does not double-subtract
///     <c>App.Screen.Y</c> on synthesized events (click, double-click) generated by the mouse interpreter.
/// </summary>
[Collection ("Application Tests")]
[Trait ("Category", "Mouse")]
public class InlineMouseOffsetTests
{
    /// <summary>
    ///     Verifies that when <c>App.Screen.Y &gt; 0</c> (inline mode), a synthesized double-click
    ///     event has the same adjusted <see cref="Mouse.ScreenPosition"/> as the original press/release
    ///     events, not a double-subtracted position.
    /// </summary>
    [Fact]
    public void RaiseMouseEvent_Inline_SynthesizedDoubleClick_HasCorrectOffset ()
    {
        // Arrange
        using IApplication app = Application.Create ();
        app.AppModel = AppModel.Inline;
        app.ForceInlinePosition = new Point (0, 10);
        app.Init (DriverRegistry.Names.ANSI);

        // Force App.Screen to have Y = 10 (simulating inline region at terminal row 10)
        app.Screen = new Rectangle (0, 10, app.Screen.Width, 5);

        // Collect all mouse events reaching Application.Mouse.MouseEvent
        List<(MouseFlags Flags, Point ScreenPosition)> receivedEvents = [];

        app.Mouse.MouseEvent += (_, e) =>
                                {
                                    receivedEvents.Add ((e.Flags, e.ScreenPosition));
                                };

        // Act: Inject two press+release cycles at terminal row 11, column 5
        // (that's row 1 within the inline region, so expected adjusted Y = 1)
        Point terminalAbsolutePosition = new (5, 11);

        // First click
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonPressed });
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonReleased });

        // Second click (should produce double-click)
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonPressed });
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonReleased });

        // Assert: All events should have Y = 1 (11 - 10), NOT Y = -9 (double subtraction)
        Point expectedAdjusted = new (5, 1);

        // Verify the double-click event has the correct position
        (MouseFlags Flags, Point ScreenPosition)? doubleClick =
            receivedEvents.FirstOrDefault (e => e.Flags.HasFlag (MouseFlags.LeftButtonDoubleClicked));

        Assert.NotNull (doubleClick);
        Assert.Equal (expectedAdjusted, doubleClick.Value.ScreenPosition);

        // Also verify single-click events have correct position
        (MouseFlags Flags, Point ScreenPosition)? singleClick =
            receivedEvents.FirstOrDefault (e => e.Flags.HasFlag (MouseFlags.LeftButtonClicked));

        Assert.NotNull (singleClick);
        Assert.Equal (expectedAdjusted, singleClick.Value.ScreenPosition);
    }

    /// <summary>
    ///     When a popover is dismissed by clicking outside it in inline mode, the recursive
    ///     <see cref="ApplicationMouse.RaiseMouseEvent"/> call must receive terminal-absolute
    ///     coordinates — not already-adjusted ones — so the inline offset subtraction happens
    ///     exactly once. Verified via <see cref="ApplicationMouse.LastMousePosition"/> which is
    ///     set after the inline adjustment in each recursive call.
    /// </summary>
    [Fact]
    public void RaiseMouseEvent_Inline_PopoverDismiss_RecursionGetsAbsoluteCoordinates () // Copilot
    {
        // Arrange
        using IApplication app = Application.Create ();
        app.AppModel = AppModel.Inline;
        app.ForceInlinePosition = new Point (0, 10);
        app.Init (DriverRegistry.Names.ANSI);
        app.Driver!.SetScreenSize (80, 25);

        Runnable top = new () { App = app };
        SessionToken? token = app.Begin (top);
        app.LayoutAndDraw ();

        // Force App.Screen.Y = 10 to simulate inline region at terminal row 10
        app.Screen = new Rectangle (0, 10, 80, 5);

        // Create and show a popover
        ApplicationPopoverTests.PopoverTestClass popover = new () { App = app };
        app.Popovers!.Register (popover);
        app.Popovers.Show (popover);

        Assert.NotNull (app.Popovers.GetActivePopover ());

        // Act: Click OUTSIDE the popover at terminal-absolute row 14 (inline-relative row 4).
        // This dismisses the popover and recurses. The recursive call adjusts coordinates:
        //   With fix:    (50, 14) → (50, 4)   [correct: 14 - 10 = 4]
        //   Without fix: (50,  4) → (50, -6)  [double subtraction: 4 - 10 = -6]
        app.Mouse.RaiseMouseEvent (new Mouse { ScreenPosition = new Point (50, 14), Flags = MouseFlags.LeftButtonPressed });

        // Assert: popover was dismissed
        Assert.False (popover.Visible, "Popover should be dismissed");

        // LastMousePosition is set from the RECURSIVE call's adjusted coordinates.
        // If double-subtraction occurred, Y would be -6 instead of 4.
        Assert.Equal (4, app.Mouse.LastMousePosition!.Value.Y);
        Assert.Equal (50, app.Mouse.LastMousePosition!.Value.X);

        app.End (token!);
        popover.Dispose ();
        top.Dispose ();
    }
}
