// Copilot

using UnitTests;

namespace ApplicationTests.MouseTests;

/// <summary>
///     Tests that mouse coordinate offset adjustment in inline mode does not double-subtract
///     <c>App.Screen.Y</c> on synthesized events (click, double-click) generated by the mouse interpreter.
/// </summary>
[Collection ("Application Tests")]
[Trait ("Category", "Mouse")]
public class InlineMouseOffsetTests
{
    /// <summary>
    ///     Verifies that when <c>App.Screen.Y &gt; 0</c> (inline mode), a synthesized double-click
    ///     event has the same adjusted <see cref="Mouse.ScreenPosition"/> as the original press/release
    ///     events, not a double-subtracted position.
    /// </summary>
    [Fact]
    public void RaiseMouseEvent_Inline_SynthesizedDoubleClick_HasCorrectOffset ()
    {
        // Arrange
        using IApplication app = Application.Create ();
        app.AppModel = AppModel.Inline;
        app.ForceInlineCursorRow = 10;
        app.Init (DriverRegistry.Names.ANSI);

        // Force App.Screen to have Y = 10 (simulating inline region at terminal row 10)
        app.Screen = new Rectangle (0, 10, app.Screen.Width, 5);

        // Collect all mouse events reaching Application.Mouse.MouseEvent
        List<(MouseFlags Flags, Point ScreenPosition)> receivedEvents = [];

        app.Mouse.MouseEvent += (_, e) =>
                                {
                                    receivedEvents.Add ((e.Flags, e.ScreenPosition));
                                };

        // Act: Inject two press+release cycles at terminal row 11, column 5
        // (that's row 1 within the inline region, so expected adjusted Y = 1)
        Point terminalAbsolutePosition = new (5, 11);

        // First click
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonPressed });
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonReleased });

        // Second click (should produce double-click)
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonPressed });
        app.InjectMouse (new Mouse { ScreenPosition = terminalAbsolutePosition, Flags = MouseFlags.LeftButtonReleased });

        // Assert: All events should have Y = 1 (11 - 10), NOT Y = -9 (double subtraction)
        Point expectedAdjusted = new (5, 1);

        // Verify the double-click event has the correct position
        (MouseFlags Flags, Point ScreenPosition)? doubleClick =
            receivedEvents.FirstOrDefault (e => e.Flags.HasFlag (MouseFlags.LeftButtonDoubleClicked));

        Assert.NotNull (doubleClick);
        Assert.Equal (expectedAdjusted, doubleClick.Value.ScreenPosition);

        // Also verify single-click events have correct position
        (MouseFlags Flags, Point ScreenPosition)? singleClick =
            receivedEvents.FirstOrDefault (e => e.Flags.HasFlag (MouseFlags.LeftButtonClicked));

        Assert.NotNull (singleClick);
        Assert.Equal (expectedAdjusted, singleClick.Value.ScreenPosition);
    }
}
